/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordRouteImport } from './routes/record'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionIdRouteImport } from './routes/question/$id'

const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionIdRoute = QuestionIdRouteImport.update({
  id: '/question/$id',
  path: '/question/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/record': typeof RecordRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/record': typeof RecordRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/record': typeof RecordRoute
  '/question/$id': typeof QuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ask' | '/auth' | '/home' | '/record' | '/question/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/auth' | '/home' | '/record' | '/question/$id'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/auth'
    | '/home'
    | '/record'
    | '/question/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  RecordRoute: typeof RecordRoute
  QuestionIdRoute: typeof QuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/$id': {
      id: '/question/$id'
      path: '/question/$id'
      fullPath: '/question/$id'
      preLoaderRoute: typeof QuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  RecordRoute: RecordRoute,
  QuestionIdRoute: QuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
